service: CognitoCloudformationResource

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito:*
      Resource:
        - "*"
plugins:
  - serverless-webpack
  - serverless-jest-plugin

functions:
  CognitoIdentity:
    handler: handler.CognitoIdentity

  CognitoIdentityServiceProvider:
    handler: handler.CognitoIdentityServiceProvider
